# Generated by Django 3.2.6 on 2021-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porzotokApp', '0004_auto_20210815_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetails',
            name='latitude',
            field=models.CharField(blank=True, default='21.4285', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='longitude',
            field=models.CharField(blank=True, default='91.9702', max_length=50, null=True),
        ),
    ]
