# Generated by Django 3.1.7 on 2021-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porzotokApp', '0005_auto_20210815_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deal_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
