# Generated by Django 3.1.7 on 2021-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porzotokApp', '0006_room_deal_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_offer_percent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='offer_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
